@url_dev=http://localhost:3055/v1/api

### signup
POST {{url_dev}}/shop/signup 
Content-Type: application/json

{
    "email": "anhht1@example.com",
    "password": "abc123",
    "name": "Tuan Anh hoc Nodejs"
}